--- List the case number, type of crime and community area for all crimes in community area number 18.---
SELECT CRIME.CASE_NUMBER, CRIME.PRIMARY_TYPE, CENSUS.COMMUNITY_AREA_NAME
FROM CHICAGO_CRIME_DATA AS CRIME
INNER JOIN CHICAGO_CENSUS_DATA AS CENSUS ON CRIME.COMMUNITY_AREA_NUMBER = CENSUS.COMMUNITY_AREA_NUMBER
WHERE CRIME.COMMUNITY_AREA_NUMBER = 18;

--- List all crimes that took place at a school. Include case number, crime type and community name. ---
SELECT CRIME.CASE_NUMBER, CRIME.PRIMARY_TYPE, CENSUS.COMMUNITY_AREA_NAME
FROM CHICAGO_CRIME_DATA AS CRIME
LEFT OUTER JOIN CHICAGO_CENSUS_DATA AS CENSUS ON CRIME.COMMUNITY_AREA_NUMBER = CENSUS.COMMUNITY_AREA_NUMBER
WHERE CRIME.LOCATION_DESCRIPTION LIKE 'SCHOOL%';

--- For the communities of Oakland, Armour Square, Edgewater and CHICAGO list the associated community_area_numbers and the case_numbers---
SELECT CRIME.CASE_NUMBER, CRIME.COMMUNITY_AREA_NUMBER, CENSUS.COMMUNITY_AREA_NAME
FROM CHICAGO_CRIME_DATA AS CRIME
FULL OUTER JOIN CHICAGO_CENSUS_DATA AS CENSUS ON CRIME.COMMUNITY_AREA_NUMBER = CENSUS.COMMUNITY_AREA_NUMBER
WHERE CENSUS.COMMUNITY_AREA_NAME IN ('Edgewater', 'CHICAGO', 'Oakland', 'Armour Square');